server:
  port: 8080

spring:
  profiles:
    active: dev
  data:
    mongodb:
      port: 27017
      host: localhost
      username: root
      password: root
      database: roombooking
      authentication-database: admin


