server:
  port: 8080

spring:
  data:
    mongodb:
      port: 27017
      database: roombooking
      #when using docker deployment, mongodb host is not localhost any more; it need to match the mongo container name
#      host: mongoDocker
      host: localhost
      #following only for local Mac docker mymongo, need to remove for aws
      username: root
      password: root
      authentication-database: admin


